import { signOut, useSession } from 'next-auth/react';
import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();

  console.log('session', session);

  return (
    <div>
      <Head>
        <title>Dogecoin Wallet</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {session ? (
          <div className='min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8'>
            <div className='max-w-md w-full space-y-8'>
              Signed in as {session.user?.email} <br />
              <button
                type='button'
                onClick={() => signOut()}
                className='group relative w-full flex justify-center py-2 px-4 border
                border-transparent text-sm font-medium rounded-md text-white bg-indigo-600
                hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset focus:ring-indigo-500'
              >
                Sign out
              </button>
            </div>
            <div className='min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8'>
              <div className='max-w-md w-full space-y-8'>
                Go to Transactions <br />
                <button
                  type='button'
                  onClick={() => router.push('/transactions')}
                  className='group relative w-full flex justify-center py-2 px-4 border
                border-transparent text-sm font-medium rounded-md text-white bg-indigo-600
                hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset focus:ring-indigo-500'
                >
                  Transactions
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className='min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8'>
            <div className='max-w-md w-full space-y-8 text-center'>
              Not signed in <br />
              <button
                type='button'
                onClick={() => {
                  router.push('/api/auth/signin');
                }}
                className='group relative w-full flex justify-center py-2 px-4 border
                  border-transparent text-sm font-medium rounded-md text-white bg-indigo-600
                  hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset focus:ring-indigo-500'
              >
                Sign in
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
