import { signOut, useSession } from 'next-auth/react';
import { useRouter } from 'next/dist/client/router';
import Head from 'next/head';
import Button from 'src/components/button';

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();

  console.log('session', session);

  return (
    <div>
      <Head>
        <title>Dogecoin Wallet</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {session ? (
          <div className='min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8'>
            <div className='max-w-md w-full space-y-8'>
              Signed in as {session.user?.email} <br />
              <Button type='button' onClick={() => signOut()}>
                Sign Out
              </Button>
            </div>
            <div className='min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8'>
              <div className='max-w-md w-full space-y-8'>
                Go to Transactions <br />
                <Button
                  type='button'
                  onClick={() => router.push('/transactions')}
                >
                  Transactions
                </Button>
              </div>
            </div>
          </div>
        ) : (
          <div className='min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8'>
            <div className='max-w-md w-full space-y-8 text-center'>
              Not signed in <br />
              <Button
                type='button'
                onClick={() => router.push('/api/auth/signin')}
              >
                Sign In
              </Button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
